spring:
  thymeleaf:
    cache: true
    mode: HTML5
  h2:
    console:
      enabled: true
  datasource:
#    schema: import.sql
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/h2/testdb;AUTO_SERVER=TRUE
#    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
#  jpa:
#      database-platform: org.hibernate.dialect.SQLServerDialect
#      hibernate:
#        ddl-auto: create-drop
#  data:
#    rest:
#      base-path: /api

# logging.level = trace > debug > info > warn > error > fatal > off
logging:
  level:
    com.example: info
    org.hibernate.SQL: debug
    org.springframework.web: info
server:
  port: 0 # 0은 랜덤

